use std::collections::HashMap;

pub fn init_game_strings(game_strings: &mut HashMap<u16, &str>) {
  game_strings.insert(0x001, "P E A N U T  3000");
  game_strings.insert(0x002, "Copyright  } 1990 Peanut Computer, Inc.\nAll rights reserved.\n\nCDOS Version 5.01");
  game_strings.insert(0x003, "2");
  game_strings.insert(0x004, "3");
  game_strings.insert(0x005, ".");
  game_strings.insert(0x006, "A");
  game_strings.insert(0x007, "@");
  game_strings.insert(0x008, "PEANUT 3000");
  game_strings.insert(0x00A, "R");
  game_strings.insert(0x00B, "U");
  game_strings.insert(0x00C, "N");
  game_strings.insert(0x00D, "P");
  game_strings.insert(0x00E, "R");
  game_strings.insert(0x00F, "O");
  game_strings.insert(0x010, "J");
  game_strings.insert(0x011, "E");
  game_strings.insert(0x012, "C");
  game_strings.insert(0x013, "T");
  game_strings.insert(0x014, "Shield 9A.5f Ok");
  game_strings.insert(0x015, "Flux % 5.0177 Ok");
  game_strings.insert(0x016, "CDI Vector ok");
  game_strings.insert(0x017, " %%%ddd ok");
  game_strings.insert(0x018, "Race-Track ok");
  game_strings.insert(0x019, "SYNCHROTRON");
  game_strings.insert(0x01A, "E: 23%\ng: .005\n\nRK: 77.2L\n\nopt: g+\n\n Shield:\n1: OFF\n2: ON\n3: ON\n\nP~: 1\n");
  game_strings.insert(0x01B, "ON");
  game_strings.insert(0x01C, "-");
  game_strings.insert(0x021, "|");
  game_strings.insert(0x022, "--- Theoretical study ---");
  game_strings.insert(0x023, " THE EXPERIMENT WILL BEGIN IN    SECONDS");
  game_strings.insert(0x024, "  20");
  game_strings.insert(0x025, "  19");
  game_strings.insert(0x026, "  18");
  game_strings.insert(0x027, "  4");
  game_strings.insert(0x028, "  3");
  game_strings.insert(0x029, "  2");
  game_strings.insert(0x02A, "  1");
  game_strings.insert(0x02B, "  0");
  game_strings.insert(0x02C, "L E T ' S   G O");
  game_strings.insert(0x031, "- Phase 0:\nINJECTION of particles\ninto synchrotron");
  game_strings.insert(0x032, "- Phase 1:\nParticle ACCELERATION.");
  game_strings.insert(0x033, "- Phase 2:\nEJECTION of particles\non the shield.");
  game_strings.insert(0x034, "A  N  A  L  Y  S  I  S");
  game_strings.insert(0x035, "- RESULT:\nProbability of creating:\n ANTIMATTER: 91.V %\n NEUTRINO 27:  0.04 %\n NEUTRINO 424: 18 %\n");
  game_strings.insert(0x036, "   Practical verification Y/N ?");
  game_strings.insert(0x037, "SURE ?");
  game_strings.insert(0x038, "MODIFICATION OF PARAMETERS\nRELATING TO PARTICLE\nACCELERATOR (SYNCHROTRON).");
  game_strings.insert(0x039, "       RUN EXPERIMENT ?");
  game_strings.insert(0x03C, "t---t");
  game_strings.insert(0x03D, "000 ~");
  game_strings.insert(0x03E, ".20x14dd");
  game_strings.insert(0x03F, "gj5r5r");
  game_strings.insert(0x040, "tilgor 25%");
  game_strings.insert(0x041, "12% 33% checked");
  game_strings.insert(0x042, "D=4.2158005584");
  game_strings.insert(0x043, "d=10.00001");
  game_strings.insert(0x044, "+");
  game_strings.insert(0x045, "*");
  game_strings.insert(0x046, "% 304");
  game_strings.insert(0x047, "gurgle 21");
  game_strings.insert(0x048, "{{{{");
  game_strings.insert(0x049, "Delphine Software");
  game_strings.insert(0x04A, "By Eric Chahi");
  game_strings.insert(0x04B, "  5");
  game_strings.insert(0x04C, "  17");
  game_strings.insert(0x12C, "0");
  game_strings.insert(0x12D, "1");
  game_strings.insert(0x12E, "2");
  game_strings.insert(0x12F, "3");
  game_strings.insert(0x130, "4");
  game_strings.insert(0x131, "5");
  game_strings.insert(0x132, "6");
  game_strings.insert(0x133, "7");
  game_strings.insert(0x134, "8");
  game_strings.insert(0x135, "9");
  game_strings.insert(0x136, "A");
  game_strings.insert(0x137, "B");
  game_strings.insert(0x138, "C");
  game_strings.insert(0x139, "D");
  game_strings.insert(0x13A, "E");
  game_strings.insert(0x13B, "F");
  game_strings.insert(0x13C, "        ACCESS CODE:");
  game_strings.insert(0x13D, "PRESS BUTTON OR RETURN TO CONTINUE");
  game_strings.insert(0x13E, "   ENTER ACCESS CODE");
  game_strings.insert(0x13F, "   INVALID PASSWORD !");
  game_strings.insert(0x140, "ANNULER");
  game_strings.insert(0x141, "      INSERT DISK ?\n\n\n\n\n\n\n\n\nPRESS ANY KEY TO CONTINUE");
  game_strings.insert(0x142, " SELECT SYMBOLS CORRESPONDING TO\n THE POSITION\n ON THE CODE WHEEL");
  game_strings.insert(0x143, "    LOADING...");
  game_strings.insert(0x144, "              ERROR");
  game_strings.insert(0x15E, "LDKD");
  game_strings.insert(0x15F, "HTDC");
  game_strings.insert(0x160, "CLLD");
  game_strings.insert(0x161, "FXLC");
  game_strings.insert(0x162, "KRFK");
  game_strings.insert(0x163, "XDDJ");
  game_strings.insert(0x164, "LBKG");
  game_strings.insert(0x165, "KLFB");
  game_strings.insert(0x166, "TTCT");
  game_strings.insert(0x167, "DDRX");
  game_strings.insert(0x168, "TBHK");
  game_strings.insert(0x169, "BRTD");
  game_strings.insert(0x16A, "CKJL");
  game_strings.insert(0x16B, "LFCK");
  game_strings.insert(0x16C, "BFLX");
  game_strings.insert(0x16D, "XJRT");
  game_strings.insert(0x16E, "HRTB");
  game_strings.insert(0x16F, "HBHK");
  game_strings.insert(0x170, "JCGB");
  game_strings.insert(0x171, "HHFL");
  game_strings.insert(0x172, "TFBB");
  game_strings.insert(0x173, "TXHF");
  game_strings.insert(0x174, "JHJL");
  game_strings.insert(0x181, " BY");
  game_strings.insert(0x182, "ERIC CHAHI");
  game_strings.insert(0x183, "         MUSIC AND SOUND EFFECTS");
  game_strings.insert(0x184, " ");
  game_strings.insert(0x185, "JEAN-FRANCOIS FREITAS");
  game_strings.insert(0x186, "IBM PC VERSION");
  game_strings.insert(0x187, "      BY");
  game_strings.insert(0x188, " DANIEL MORAIS");
  game_strings.insert(0x18B, "       THEN PRESS FIRE");
  game_strings.insert(0x18C, " PUT THE PADDLE ON THE UPPER LEFT CORNER");
  game_strings.insert(0x18D, "PUT THE PADDLE IN CENTRAL POSITION");
  game_strings.insert(0x18E, "PUT THE PADDLE ON THE LOWER RIGHT CORNER");
  game_strings.insert(0x258, "      Designed by ..... Eric Chahi");
  game_strings.insert(0x259, "    Programmed by...... Eric Chahi");
  game_strings.insert(0x25A, "      Artwork ......... Eric Chahi");
  game_strings.insert(0x25B, "Music by ........ Jean-francois Freitas");
  game_strings.insert(0x25C, "            Sound effects");
  game_strings.insert(0x25D, "        Jean-Francois Freitas\n             Eric Chahi");
  game_strings.insert(0x263, "              Thanks To");
  game_strings.insert(0x264, "           Jesus Martinez\n\n          Daniel Morais\n\n        Frederic Savoir\n\n      Cecile Chahi\n\n    Philippe Delamarre\n\n  Philippe Ulrich\n\nSebastien Berthet\n\nPierre Gousseau");
  game_strings.insert(0x265, "Now Go Out Of This World");
  game_strings.insert(0x190, "Good evening professor.");
  game_strings.insert(0x191, "I see you have driven here in your\nFerrari.");
  game_strings.insert(0x192, "IDENTIFICATION");
  game_strings.insert(0x193, "Monsieur est en parfaite sante.");
  game_strings.insert(0x194, "Y\n");
  game_strings.insert(0x193, "AU BOULOT !!!\n");
}